from jenkins/jenkins:lts-jdk21

user root

run apt-get update && \
    apt-get install -y curl unzip ca-certificates gnupg lsb-release && \
    rm -rf /var/lib/apt/lists/*

run arch=$(uname -m) && \
    if [ "$arch" = "x86_64" ]; then \
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"; \
    else \
      curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"; \
    fi && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf aws awscliv2.zip

run curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm -f kubectl

run apt-get update && \
    apt-get install -y docker.io && \
    rm -rf /var/lib/apt/lists/*

run aws --version && kubectl version --client && docker --version