apiVersion: apps/v1
kind: Deployment
metadata:
  name: skala-devops
  labels:
    app: skala-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skala-devops
  template:
    metadata:
      labels:
        app: skala-devops
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - name: skala-devops
          image: __IMAGE__
          imagePullPolicy: Always
          ports:
            - containerPort: 80
