apiVersion: v1
kind: Service
metadata:
  name: skala-devops
  labels:
    app: skala-devops
spec:
  selector:
    app: skala-devops
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
